# Generated by Django 5.2 on 2025-08-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Gaming', 'Gaming'), ('Audio', 'Audio'), ('Office', 'Office'), ('Accessories', 'Accessories')], default='Accessories', max_length=50)),
                ('image', models.CharField(default='fas fa-box', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
